name: Running Examples

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install locally
      run: |
        python3 -m pip install .

    - name: Run all Examples
      run: |
        for example in examples/*.py; do
          python3 "$example"
        done
